name: Clara
main: com.kNoAPP.Clara.Clara
version: 1.0.0
commands:
    clara:
        description: CLARA Manager
    import:
        description: Import Files
    export:
        description: Export Files