name: Clara
main: com.kNoAPP.Clara.Clara
version: 1.2.0
commands:
    clara:
        description: Clara Manager
    world:
        description: Access a World
    stay:
        description: Opt-out of Restoration