name: Clara
main: com.kNoAPP.Clara.Clara
version: 1.0.5
commands:
    clara:
        description: Clara Manager
    import:
        description: Import Files
    export:
        description: Export Files